{
 "title": "carlos-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Merlin battery capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "android_battery_capacity_percent{instance=\"192.168.50.1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin Inet RX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "android_network_total_bytes{direction=\"received\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad Cpu Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"node_hwmon_temp_celsius\", chip=\"platform_coretemp_0\", instance=\"node_exporter:9100\", job=\"node_exporter\", sensor=\"temp1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpan Fan",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_thinkpad_hwmon\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasmota Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_uptime_seconds{instance=\"192.168.50.204\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"renot9 ping\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasmota status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"192.168.50.204\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad power supply",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_power_supply_power_watt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thinkpad Ram Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Esp32 Boot count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_boot_count{instance=\"192.168.50.204\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Google",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"ping_dns_google\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin Cpu Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "android_cpu_temperature_celsius{instance=\"192.168.50.1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin Inet TX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "android_network_total_bytes{direction=\"transmitted\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpan Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(node_power_supply_energy_watthour{power_supply=~\"BAT[01]\"})\n/\n  sum(node_power_supply_energy_full{power_supply=~\"BAT[01]\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Esp32 Free Ram",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_memory_free_bytes{instance=\"192.168.50.204\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpan charging",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_online{instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin Battery Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "android_battery_temperature_celsius{instance=\"192.168.50.1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin charger",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "android_battery_is_charging", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Esp32 Kipas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_relay2_state{instance=\"192.168.50.204\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Esp32 Lampu",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_relay1_state{instance=\"192.168.50.204\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}